import { Button, VerticalBox } from "std-widgets.slint";
import { SideBar } from "ui/side_bar.slint";

export component AppWindow inherits Window {
     preferred-width: 700px;
     preferred-height: 500px;
     HorizontalLayout {
            side-bar := SideBar {
                title: @tr("Slint Widgets Gallery");
                model: [@tr("Menu" => "Controls"), @tr("Menu" => "ListView"), @tr("Menu" => "TableView"), @tr("Menu" => "TextEdit"), @tr("Menu" => "Easings"), @tr("Menu" => "About")];
            }
            /*
            if(side-bar.current-item == 0) : ControlsPage {}
            if(side-bar.current-item == 1) : ListViewPage {}
            if(side-bar.current-item == 2) : TableViewPage {}
            if(side-bar.current-item == 3) : TextEditPage {}
            if(side-bar.current-item == 4) : EasingsPage {}
            if(side-bar.current-item == 5) : AboutPage {}
            */
        }
}
